import styles from "@/styles/heroSection.module.css";
import style from "@/styles/blog.module.css";
import Link from "next/link";
import Head from "next/head";
import Image from 'next/image';

export async function getServerSideProps() {

  const res = await fetch('http://localhost:3000/api/hello')
  const data = await res.json()

  return { props: { data } }
}

const Home = ({ data }) => {


  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./favicon.ico" />
      </Head>
      <>
        <div className={styles.space}>
          {data && data.news && data.news.slice(0, 1).map((item) => (<div className={styles.large}>
            <div className={styles.overlay}></div>

            <Image
              src={item.url}
              className={styles.imgdata}
              width={500}
              height={500}
              alt={item.alt}
            />
            <div className={styles.buttonContainer}>
              <button className={`${styles.redButton} ${styles.smallButton}`}>{item.name}</button>
              <h2 className={styles.herofont}>{item.title}</h2>

              <div className={styles.icon}>
                <i className="fa-solid fa-user"></i> &nbsp;<label >{item.name}</label>&nbsp;&nbsp;&nbsp;&nbsp;
                <i className="fa-solid fa-user"></i> &nbsp;<label>{item.date}</label>&nbsp;&nbsp;&nbsp;&nbsp;
                <i className="fa-solid fa-user"></i> &nbsp;<label>{item.commeants}</label>&nbsp;&nbsp;&nbsp;&nbsp;
              </div>
            </div>
          </div>))}
          <div className={styles.main}>
            {data && data.news && data.news.slice(0, 2).map((item) => (<div className={styles.small}>
              <div className={styles.overlay}></div>

              <Image
                src={item.url}
                className={styles.imgdata}
                width={247}
                height={248}
                alt={item.alt}
              />
              <div className={styles.buttonContainer}>
                <button className={`${styles.redButton} ${styles.smallButton}`}>{item.name}</button>
                <h2 className={styles.herfonts}>{item.title}</h2>

                <div className={styles.icon}>
                  <i className="fa-solid fa-user"></i> &nbsp;<label >{item.name}</label>&nbsp;&nbsp;&nbsp;&nbsp;
                  <i className="fa-solid fa-user"></i> &nbsp;<label>{item.date}</label>&nbsp;&nbsp;&nbsp;&nbsp;
                  <i className="fa-solid fa-user"></i> &nbsp;<label>{item.commeants}</label>&nbsp;&nbsp;&nbsp;&nbsp;
                </div>
              </div>
            </div>))}

          </div>
        </div>
      </>
      <div className={styles.header}>

        <span>Breacking news : </span><label>Natwar Singh writes on champion of the downtrodden Dr BR</label>

      </div>

      <div className="container mt-4">

        <div className="row justify-content-between ">
          <div className="col-lg-7 bg-light p-3 h-100">
            <div className="row bg-dark m-2 p-2 text-light fw-bold">Latest news</div>

            {data && data.news && data.news.map((item) => (
              <div className="row p-2 ">
                <div className="col-md-4 ">
                  <div className={style.buttonContainer}>

                    <Image
                      src={item.url}
                      className={style.squareimage}
                      width={180}
                      height={180}
                      alt={item.alt}
                    />
                    <button className={style.redButton}>{item.name}</button>
                  </div>
                </div>
                <div className="col-md-8 mt-auto mb-auto">
                  <Link href={`/Blogs/${item.id}`} className={style.a}> <h2 className={`${style.herfonts}`}>{item.title}</h2></Link>
                  <div className={style.icon}>
                    <i className="fa-solid fa-user"></i> &nbsp;<label >{item.name}</label>&nbsp;&nbsp;
                    <i className="fa-solid fa-user"></i> &nbsp;<label>{item.date}</label>&nbsp;&nbsp;
                    <i className="fa-solid fa-user"></i> &nbsp;<label>{item.commeants}</label>&nbsp;&nbsp;
                  </div>
                  <p className={style.parcolor}> {item.news}</p>
                </div>
              </div>))}

          </div>
          {/* Second Column */}
          <div className={`col-lg-4 bg-light p-3 h-25`}>
            <div className="row bg-dark m-2 p-2 text-light fw-bold">Latest news</div>
            {data && data.news && data.news.slice(0, 1).map((item) => (<>
              <div className="row p-2">
                <div className="col-md-12 mb-1">
                  <div className={style.buttonContainer}>

                    <Image
                      src={item.url}
                      className={style.squareimage}
                      width={180}
                      height={180}
                      alt={item.alt}
                    />
                    <button className={style.redButton}>{item.name}</button>
                  </div>
                </div>
              </div>
              <div className="row p-2">
                <div className="col-md-12 mb-2">
                  <Link href={`/Blogs/${item.id}`} className={style.a}>  <h2 className={style.herfonts}>{item.title}</h2></Link>
                  <div className={style.icon}>
                    <i className="fa-solid fa-user"></i> &nbsp;<label >{item.name}</label>&nbsp;&nbsp;
                    <i className="fa-solid fa-user"></i> &nbsp;<label>{item.date}</label>&nbsp;&nbsp;
                    <i className="fa-solid fa-user"></i> &nbsp;<label>06</label>&nbsp;&nbsp;
                  </div>
                  <p className={style.parcolor}>
                    {item.news}
                  </p>

                </div>
              </div>
            </>))}

            {data && data.news && data.news.slice(0, 3).map((item) => (
              <div className="row p-2">
                <div className="col-md-4">

                  <Image
                    src={item.url}
                    className={style.squareimagesmall}
                    width={180}
                    height={180}
                    alt={item.alt}
                  />
                </div>
                <div className="col-md-8 mt-auto mb-auto">
                  <Link href={`/Blogs/${item.id}`} className={style.a}>  <h2 className={style.herofont}>{item.title}</h2></Link>
                  <div className={`${style.icon} `}>

                    <i className="fa-solid fa-user"></i> &nbsp;<label>{item.date}</label>&nbsp;&nbsp;
                    <i className="fa-solid fa-user"></i> &nbsp;<label>06</label>&nbsp;&nbsp;
                  </div>

                </div>
              </div>))}

          </div>



        </div>
      </div>
    </>
  )
}

export default Home