import styles from "@/styles/home.module.css";
import Head from "next/head"
import Image from 'next/image';
export async function getServerSideProps(context) {
  const { singleBlog } = context.params;
  const res = await fetch(`http://localhost:3000/api/${singleBlog}`);
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}

function SingleBlog({ data }) {
  return (
    <>
      <Head>
        <title>{data?.news?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content={data?.news?.name} />
        <link rel="icon" href="./favicon.ico" />
      </Head>
      <>
        <header className="py-5 bg-light border-bottom mb-4">
          <div className="container">
            <div className="text-center my-5">
              <h1 className="fw-bolder">Welcome to Blog Home!</h1>
              <p className="lead mb-0">
                A new Lates News See and Incriment Your Knowleng
              </p>
            </div>
          </div>
        </header>
        <div className="container">
          <div className="row">
            <div className="col-lg-8">
              <div className="card mb-4">
                <Image
                  src={data?.news?.url}
                  className="card-img-top"
                  width={500}
                  height={500}
                  alt={data?.news?.url} />
                <div className="card-body">
                  <div className="small text-muted">{data?.news?.date}</div>
                  <h2 className="card-title">{data?.news?.title}</h2>
                  <p className="card-text">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    Reiciendis aliquid atque, nulla? Quos cum ex quis soluta, a
                    laboriosam. Dicta expedita corporis animi vero voluptate
                    voluptatibus possimus, veniam magni quis!
                  </p>
                  <button className={styles.redButton}>{data?.news?.name}</button>
                </div>
              </div>
            </div>
            <div className="col-lg-4">
              <div className="card mb-4">
                <div className="card-header">Side Widget</div>
                <div className="card-body">
                  Now let me explain this braking system to you. If you’ve never been on a mountain coaster, each car can fit one adult and if you have a small child, they can ride on a seat in between your legs. When you sit down in the coaster, on each side of you is a lever. How it works is, that if you want your coaster car to move, you must hold both levers down as far as they will go. If you come up even a little, your car starts to slow down. If you stop holding them altogether, your car will come to a complete stop.
                  When we were being given instructions on how to operate the coaster, the employees were extremely adamant about everyone pushing down on their levers as hard as they could. “Keep holding your levers down, DO NOT STOP ON THE TRACKS!” I can imagine that would be a terrible pile-up if someone stopped on the tracks---that’s why you sign a waiver, people! Can I just tell you that it was incredibly difficult to keep those levers down for the duration of the ride? There was resistance happening, my back started hurting. My body was getting whipped around. It took everything within me to hold on.
                </div>
              </div>
            </div>
          </div>
        </div>
      </>

    </>
  );
}

export default SingleBlog;
