import style from "@/styles/blog.module.css";
import Link from "next/link";
import Head from "next/head";
import Image from 'next/image';


export async function getServerSideProps() {

    const res = await fetch('http://localhost:3000/api/hello')
    const data = await res.json()

    return { props: { data } }
}


const Blog = ({ data }) => {
    return (
        <>
            <Head>
                <title>Blog Pgae</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="./favicon.ico" />
            </Head>
            <div className="container mt-4">

                <div className="row justify-content-between ">
                    <div className="col-lg-7 bg-light p-3 h-100">
                        <div className="row bg-dark m-2 p-2 text-light fw-bold">Latest news</div>

                        {data && data.news && data.news.map((item) => (
                            <div className="row p-2 ">
                                <div className="col-md-4 ">
                                    <div className={style.buttonContainer}>
                                        {/* <img
              src={item.url}
              alt="Square Image"
              className={style.squareimage}
            /> */}
                                        <Image
                                            src={item.url}
                                            className={style.squareimage}
                                            width={247}
                                            height={247}
                                            alt={item.alt}
                                        />
                                        <button className={style.redButton}>{item.name}</button>
                                    </div>
                                </div>
                                <div className="col-md-8 mt-auto mb-auto">
                                    <Link href={`/Blogs/${item.id}`} className={style.a}> <h2 className={`${style.herfonts}`}>{item.title}</h2></Link>
                                    <div className={style.icon}>
                                        <i className="fa-solid fa-user"></i> &nbsp;<label >{item.name}</label>&nbsp;&nbsp;
                                        <i className="fa-solid fa-user"></i> &nbsp;<label>{item.date}</label>&nbsp;&nbsp;
                                        <i className="fa-solid fa-user"></i> &nbsp;<label>{item.commeants}</label>&nbsp;&nbsp;
                                    </div>
                                    <p className={style.parcolor}> {item.news}</p>
                                </div>
                            </div>))}

                    </div>
                    {/* Second Column */}
                    <div className={`${style.secondcol} col-lg-4 bg-light p-3 h-25`}>
                        <div className="row bg-dark m-2 p-2 text-light fw-bold">Latest news</div>
                        {data && data.news && data.news.slice(0, 1).map((item) => (<>
                            <div className="row p-2">
                                <div className="col-md-12 mb-1">
                                    <div className={style.buttonContainer}>
                                        {/* <img
              src={item.url}
              alt="Square Image"
              className={style.squareimage}
            /> */}
                                        <Image
                                            src={item.url}
                                            className={style.squareimage}
                                            width={247}
                                            height={247}
                                            alt={item.alt}
                                        />
                                        <button className={style.redButton}>{item.name}</button>
                                    </div>
                                </div>
                            </div>
                            <div className="row p-2">
                                <div className="col-md-12 mb-2">
                                    <Link href={`/Blogs/${item.id}`} className={style.a}>  <h2 className={style.herfonts}>{item.title}</h2></Link>
                                    <div className={style.icon}>
                                        <i className="fa-solid fa-user"></i> &nbsp;<label >{item.name}</label>&nbsp;&nbsp;
                                        <i className="fa-solid fa-user"></i> &nbsp;<label>{item.date}</label>&nbsp;&nbsp;
                                        <i className="fa-solid fa-user"></i> &nbsp;<label>06</label>&nbsp;&nbsp;
                                    </div>
                                    <p className={style.parcolor}>
                                        {item.news}
                                    </p>

                                </div>
                            </div>
                        </>))}

                        {data && data.news && data.news.slice(0, 3).map((item) => (
                            <div className="row p-2">
                                <div className="col-md-4">
                                    {/* <img
            src={item.url}
            alt="Small Image"
            className={style.squareimagesmall}
          /> */}
                                    <Image
                                        src={item.url}
                                        className={style.squareimagesmall}
                                        width={247}
                                        height={250}
                                        alt={item.alt}
                                    />
                                </div>
                                <div className="col-md-8 mt-auto mb-auto">
                                    <Link href={`/Blogs/${item.id}`} className={style.a}>  <h2 className={style.herofont}>{item.title}</h2></Link>
                                    <div className={`${style.icon} `}>

                                        <i className="fa-solid fa-user"></i> &nbsp;<label>{item.date}</label>&nbsp;&nbsp;
                                        <i className="fa-solid fa-user"></i> &nbsp;<label>06</label>&nbsp;&nbsp;
                                    </div>

                                </div>
                            </div>))}

                    </div>



                </div>
            </div>
        </>






    )
}

export default Blog


